version: 3.7.0-build{build}
install:
- cmd: nuget sources add -Name MyGet-CI -Source http://myget.org/f/damiendennehy/
- nuget restore
build:
  verbosity: minimal
test:
  assemblies: '**\*.tests.dll'
  categories:
  - none