version: 1.0.0-build{build}
install:
- cmd: nuget sources add -Name MyGet-CI -Source http://myget.org/f/damiendennehy/
- nuget restore
cache:
- C:\Users\appveyor\.dnx\runtimes
- C:\Users\appveyor\.dnx\packages
build:
  verbosity: minimal
test:
  assemblies: '**\*.tests.dll'
  categories:
  - none