version: 1.0.0-build{build}
install:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/A/3/8/A38489F3-9777-41DD-83F8-2CBDFAB2520C/packages/DotNetCore.1.0.0-SDK.Preview2-x64.exe','core.exe')


    core.exe /install /quiet /norestart


    dotnet restore
cache: C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
build:
  verbosity: minimal
test:
  assemblies: '**\*.tests.dll'
  categories:
  - none