version: 1.0.0-build{build}
environment:
  VisualStudioVersion: 14.0
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: 1.0.0.{build}
  assembly_informational_version: '1.0.0-build{build}'
build:
  project: Imgur.API.Integration.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal